name: CI/CD Pipeline - ms-alertas

on:
  push:
    branches: ["main", "develop", "feature/ms-alertas-final"]
    paths:
      - "ms-alertas/**"
  pull_request:
    branches: ["main", "develop"]

# 🚀 Hemos eliminado la variable env: FORCE_JAVASCRIPT_ACTIONS_TO_NODE24
# para que GitHub use el motor nativo de las acciones.

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ms-alertas

    steps:
      # v4 es la versión estable actual que ya soporta los runners modernos
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./ms-alertas/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Project
        run: npm run build
